import { CowData, GrowthDataPoint, ScaleHistory } from './types';

// Historical monthly growth data for the main chart (6 months timeline)
export const initialGrowthData: GrowthDataPoint[] = [
  { tanggal: 'Jan 2026', beratRataRata: 395, adgRataRata: 0.72 },
  { tanggal: 'Feb 2026', beratRataRata: 402, adgRataRata: 0.75 },
  { tanggal: 'Mar 2026', beratRataRata: 408, adgRataRata: 0.78 },
  { tanggal: 'Apr 2026', beratRataRata: 414, adgRataRata: 0.82 },
  { tanggal: 'Mei 2026', beratRataRata: 418, adgRataRata: 0.80 },
  { tanggal: 'Jun 2026', beratRataRata: 420, adgRataRata: 0.81 },
];

// Initial simulated cows dataset for DSS table
export const initialCowsData = [
  {
    id: 1,
    cow_code: 'RFID-9281-A',
    name: 'Bimo',
    breed: 'Sapi Limousin',
    gender: 'jantan',
    birth_date: '2024-05-10',
    owner: 'Budi Santoso',
    status: 'active',
    last_weight: 485,
    last_adg: 0.85,
  },
  {
    id: 2,
    cow_code: 'RFID-4210-B',
    name: 'Seno',
    breed: 'Sapi Simmental',
    gender: 'jantan',
    birth_date: '2024-07-15',
    owner: 'Slamet Hariadi',
    status: 'active',
    last_weight: 462,
    last_adg: 0.72,
  },
  {
    id: 3,
    cow_code: 'RFID-1102-C',
    name: 'Joko',
    breed: 'Sapi Brahman',
    gender: 'jantan',
    birth_date: '2025-01-20',
    owner: 'Budi Santoso',
    status: 'active',
    last_weight: 382,
    last_adg: 0.28,
  },
  {
    id: 4,
    cow_code: 'RFID-8841-D',
    name: 'Lestari',
    breed: 'Sapi PO (Ongole)',
    gender: 'betina',
    birth_date: '2024-10-05',
    owner: 'Agus',
    status: 'active',
    last_weight: 415,
    last_adg: 0.65,
  },
  {
    id: 5,
    cow_code: 'RFID-5100-E',
    name: 'Marni',
    breed: 'Sapi Bali',
    gender: 'betina',
    birth_date: '2025-03-12',
    owner: 'Slamet Hariadi',
    status: 'active',
    last_weight: 310,
    last_adg: -0.1,
  },
  {
    id: 6,
    cow_code: 'RFID-3392-F',
    name: 'Gatot',
    breed: 'Sapi Limousin',
    gender: 'jantan',
    birth_date: '2024-03-01',
    owner: 'Budi Santoso',
    status: 'active',
    last_weight: 495,
    last_adg: 0.91,
  },
];

// Scales weigh history log from the ESP32 IoT nodes
export const scalesHistoryData: ScaleHistory[] = [
  {
    id: 'scale-1',
    rfid: 'RFID-9281-A',
    jenisSapi: 'Sapi Limousin',
    tanggalTimbang: '18 Jul 2026, 06:30 WITA',
    beratSebelumnya: 479,
    beratSekarang: 485,
    selisih: 6,
    petugas: 'Slamet Hariadi',
  },
  {
    id: 'scale-2',
    rfid: 'RFID-4210-B',
    jenisSapi: 'Sapi Simmental',
    tanggalTimbang: '18 Jul 2026, 06:15 WITA',
    beratSebelumnya: 457,
    beratSekarang: 462,
    selisih: 5,
    petugas: 'Slamet Hariadi',
  },
  {
    id: 'scale-3',
    rfid: 'RFID-3392-F',
    tanggalTimbang: '17 Jul 2026, 15:45 WITA',
    jenisSapi: 'Sapi Limousin',
    beratSebelumnya: 488,
    beratSekarang: 495,
    selisih: 7,
    petugas: 'Budi Santoso',
  },
  {
    id: 'scale-4',
    rfid: 'RFID-5100-E',
    tanggalTimbang: '17 Jul 2026, 14:10 WITA',
    jenisSapi: 'Sapi Bali',
    beratSebelumnya: 312,
    beratSekarang: 310,
    selisih: -2,
    petugas: 'Budi Santoso',
  },
  {
    id: 'scale-5',
    rfid: 'RFID-9041-J',
    tanggalTimbang: '16 Jul 2026, 09:20 WITA',
    jenisSapi: 'Sapi Limousin',
    beratSebelumnya: 514,
    beratSekarang: 520,
    selisih: 6,
    petugas: 'Budi Santoso',
  }
];
